<?php

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function searchblox_help($route_name, 
    Drupal\Core\Routing\RouteMatchInterface $route_match)
{
    
    switch ($route_name) {
        case 'help.page.searchblox':
            $output = '';
            $output .= '<h3>' . t('How To Configure') . '</h3>';
            $output .= '<p>' . t('<ol>
                                    <li> Go to <a href="@settings" target="_blank" > SearchBlox settings page </a> to configure your settings. </li>
                                    <li> Enter the name of the collection you have created in your SearchBlox application for indexing your site. </li>
                                    <li> Index your site to this collection , after this step you will be able to show your search results from SearchBlox application.</li>
                                    <li> Now on the <a href="@collection" target="_blank" > Search Collection Page </a> Mark those collection from where you need to show search results on your site , if you need to show your results from all the collections
                                            available on your application don\'t mark any collection. By default It shows results from all the available collection.
                                    </li>
                                  </ol>    ', array(
                '@settings' => \Drupal::url('searchblox.admin.config'),
                '@collection' => \Drupal::url('searchblox.collection_page')
            ));
            $output .= '<h3>' . t('Frontend Configuration') . '</h3>';
            $output .= '<dl>';
            $output .= '<dt>' . t('SearchBlox Search') . '</dt>';
            $output .= '<dd>' . t('To show SearchBlox Search Block in your content area Go to <a href="' . \Drupal::url('block.admin_display') . '" target="_blank" > structure/blocks </a> 
                      scroll down to disabled blocks you will see <strong>SearchBlox Search </strong>, drag it to your content area and save option. You can now 
                      configure your block for additional settings i.e set permissions, show block on all pages or only specific page etc. 

                      ') . '</dd>';
            $output .= '</dl>';
            
            return $output;
            break;
    }
}

/**
 * Load Necessary files.
 *
 */


if (function_exists('module_load_include')) {
    module_load_include('inc', 'searchblox', 'helper/searchblox_functions');
    module_load_include('inc', 'searchblox', 'helper/searchblox_api_functions');
    module_load_include('inc', 'searchblox', 'helper/searchblox_curl_functions');
	module_load_include('inc', 'searchblox', 'helper/searchblox_frontend_functions');
} else {
    return;
}

/**
 * Implements hook_theme().
 */

function searchblox_theme($existing, $type, $theme, $path)
{
    
    global $base_url;

    $theme = array(
        'searchblox_full_page' => array(
            'path' => drupal_get_path('module', 'searchblox') . '/theme',
            'template' => 'searchblox_full_page',
            'variables' => array(
                'table_data' => searchblox_get_index_page_table(),
                'searchblox_location' => searchblox_location()
            )
        ),
        'searchblox_frontend_view' => array(
            'path' => drupal_get_path('module', 'searchblox') . '/theme',
            'template' => 'searchblox_frontend_view',
            'variables' => array(
                'baseUrl' => $base_url
            )

        ),
        'searchblox_header' => array(
            'path' => drupal_get_path('module', 'searchblox') . '/theme',
            'template' => 'searchblox_header'
        )
    );
    
    return $theme;
}

/**
 * Pass Data To Js File
 */

function searchblox_add_js_settings()
{
    global $base_url;
    $results = searchblox_get_nodes_from_db($range = false);
    $rowCount = count($results);
    return ["base_url" => $base_url , "total_docs" => $rowCount];
}